name: CI-CD pipeline

on:
  push:
    branches:
      - main

jobs:
  test-build-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: GHCR login
        run: echo "${{ secrets.GHCR_TOKEN }}" | docker login ghcr.io -u ${{ secrets.GITHUB_USERNAME }} --password-stdin

      - name: Build docker image
        run: docker build -t ghcr.io/${{ secrets.GITHUB_USERNAME }}/flaskp:latest .
        
      - name: Push to GHCR
        run: docker push ghcr.io/${{ secrets.GITHUB_USERNAME }}/flaskp:latest

      - name: Docker run
        run: docker run -d --name testcont -p 5000:5000 ghcr.io/${{ secrets.GITHUB_USERNAME }}/flaskp:latest

      - name: Check working status
        run: |
          for i in {1..15}; do
            if curl -sf http://localhost:5000; then
              echo "Application working.."
              exit 0
            fi
            echo "Waiting for application.."
            sleep 3
          done
          echo "Application failed to start.."
          exit 1

      - name: Check running containers
        run: docker ps

      - name: Check logs
        run: docker logs testcont

      - name: Remove container
        run: docker rm -f testcont
