name: CI-CD-Pipeline

on:
  push:
    branches:
      - main

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
      - name: checkout-code
        uses: actions/checkout@v4

      - name: login to Github Content Registry
        run: echo "${{secrets.GHCR_TOKEN}}" | docker login ghcr.io -u "${{secrets.GITH_USERNAME}}" --password-stdin

      - name: build image
        run: docker build -t ghcr.io/${{secrets.GITH_USERNAME}}/my-ci-cd:latest .

      - name: push image
        run: docker push ghcr.io/${{secrets.GITH_USERNAME}}/my-ci-cd:latest 

      - name: run container
        run: docker run -d -p 5000:5000 --name testcont ghcr.io/${{secrets.GITH_USERNAME}}/my-ci-cd:latest

      - name: check container
        run: docker ps

      - name: logs
        run: docker logs testcont

      - name: wait for app
        run: sleep 15

      - name: stop container
        run: docker stop testcont

      - name: remove container
        run: docker rm testcont
